version: '3.2'

services:
  db:
    container_name: story_db
    environment:
        POSTGRES_DB: story
        POSTGRES_USER: postgres
        POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:14
    volumes:
      - ./yoyo/init:/docker-entrypoint-initdb.d
    ports:
    - 5432:5432


  story:
    restart: always
    build: .
    volumes:
      - ./:/app
    command: gunicorn story.app:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - 8080:8080
    depends_on:
      - db


volumes:
  dbdata: