version: "3.2"

services:
  db:
    container_name: myning_db
    environment:
      POSTGRES_DB: myning
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:14
    volumes:
      - ./yoyo/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  dbdata:
