version: '3.2'

services:
  postgres:
      image: postgres:14
      volumes:
      - ./:/app/yoyo/init/user.sql
      environment:
          - POSTGRES_USER=dev
          - POSTGRES_PASSWORD=pass
          - POSTGRES_DB=story
      ports:
      - 5432:5432


  story:
    build: .
    volumes:
      - ./:/app
    command: gunicorn story.app:app -b :8080 --worker-class aiohttp.GunicornWebWorker --reload --access-logfile -
    ports:
      - 8080:8080
    depends_on:
      - postgres


volumes:
  dbdata: